-- Tabel referensi generik untuk jenis sepatu, fitur, jenis aktivitas, aksi maintenance
CREATE TABLE ref_code (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type              VARCHAR(50)  NOT NULL,
    type_name         VARCHAR(50)  NOT NULL,
    code              VARCHAR(50)  NOT NULL,
    code_name         VARCHAR(50)  NOT NULL,
    description       TEXT,

    creation_time     TIMESTAMP    NOT NULL DEFAULT now(),
    modification_time TIMESTAMP    NOT NULL DEFAULT now(),
    created_by        VARCHAR(100) NOT NULL DEFAULT 'system',
    modified_by       VARCHAR(100) NOT NULL DEFAULT 'system',
    CONSTRAINT uq_ref_code_type_code UNIQUE (type, code)
);

-- Data table utama sepatu.
CREATE TABLE shoe (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR(100)  NOT NULL,
    brand                       VARCHAR(100)  NOT NULL,
    model                       VARCHAR(100)  NOT NULL,
    shoe_type_ref_id            BIGINT        NOT NULL REFERENCES ref_code (id),
    color                       VARCHAR(50)   NOT NULL,
    size_value                  DECIMAL(4, 1) NOT NULL,
    size_system                 VARCHAR(2)    NOT NULL,
    weight_grams                INT,
    purchase_date               DATE          NOT NULL,
    purchase_price              DECIMAL(12, 2),
    target_lifespan_km          INT,
    retired                     BOOLEAN       NOT NULL DEFAULT FALSE,
    retired_at                  DATE,

    total_distance_km           DECIMAL(10, 2) NOT NULL DEFAULT 0,
    usage_count                 INT            NOT NULL DEFAULT 0,
    usage_count_since_last_wash INT            NOT NULL DEFAULT 0,
    last_used_at                DATE,
    last_washed_at              DATE,

    creation_time               TIMESTAMP      NOT NULL DEFAULT now(),
    modification_time           TIMESTAMP      NOT NULL DEFAULT now(),
    created_by                  VARCHAR(100)   NOT NULL DEFAULT 'system',
    modified_by                 VARCHAR(100)   NOT NULL DEFAULT 'system',
    CONSTRAINT ck_shoe_size_system CHECK (size_system IN ('EU', 'US', 'UK', 'CM'))
);

-- Relasi many-to-many sepatu dengan fitur (tabel penghubung, tanpa kolom audit)
CREATE TABLE shoe_feature_map (
    shoe_id        BIGINT NOT NULL REFERENCES shoe (id) ON DELETE CASCADE,
    feature_ref_id BIGINT NOT NULL REFERENCES ref_code (id),
    PRIMARY KEY (shoe_id, feature_ref_id)
);

-- log untuk penggunaan sepatu
CREATE TABLE usage_log (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoe_id              BIGINT        NOT NULL REFERENCES shoe (id),
    activity_date        DATE          NOT NULL,
    distance_km          DECIMAL(6, 2) NOT NULL,
    activity_type_ref_id BIGINT        NOT NULL REFERENCES ref_code (id),
    duration_minutes     INT,
    notes                TEXT,

    creation_time        TIMESTAMP     NOT NULL DEFAULT now(),
    modification_time    TIMESTAMP     NOT NULL DEFAULT now(),
    created_by           VARCHAR(100)  NOT NULL DEFAULT 'system',
    modified_by          VARCHAR(100)  NOT NULL DEFAULT 'system',
    CONSTRAINT ck_usage_log_distance CHECK (distance_km >= 0)
);

CREATE INDEX idx_usage_log_shoe_date ON usage_log (shoe_id, activity_date);

-- table catatan pemeliharaan sepatu
CREATE TABLE maintenance_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoe_id           BIGINT       NOT NULL REFERENCES shoe (id),
    action_ref_id     BIGINT       NOT NULL REFERENCES ref_code (id),
    action_date       DATE         NOT NULL,
    notes             TEXT,

    creation_time     TIMESTAMP    NOT NULL DEFAULT now(),
    modification_time TIMESTAMP    NOT NULL DEFAULT now(),
    created_by        VARCHAR(100) NOT NULL DEFAULT 'system',
    modified_by       VARCHAR(100) NOT NULL DEFAULT 'system'
);

CREATE INDEX idx_maintenance_log_shoe_date ON maintenance_log (shoe_id, action_date);
