spring.application.name=shoe-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/capatu_shoe
spring.datasource.username=capatu
spring.datasource.password=capatu

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
