CREATE TABLE reminder (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoe_id           BIGINT       NOT NULL,
    shoe_name         VARCHAR(100) NOT NULL,
    type              VARCHAR(20)  NOT NULL,
    severity          VARCHAR(20)  NOT NULL,
    message           VARCHAR(255) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    detected_at       TIMESTAMP    NOT NULL,
    acknowledged_at   TIMESTAMP,
    resolved_at       TIMESTAMP,

    creation_time     TIMESTAMP    NOT NULL DEFAULT now(),
    modification_time TIMESTAMP    NOT NULL DEFAULT now(),
    created_by        VARCHAR(100) NOT NULL DEFAULT 'system',
    modified_by       VARCHAR(100) NOT NULL DEFAULT 'system',
    CONSTRAINT ck_reminder_type CHECK (type IN ('WASH', 'REPLACE', 'ROTATION')),
    CONSTRAINT ck_reminder_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_reminder_status CHECK (status IN ('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED'))
);

CREATE UNIQUE INDEX uq_reminder_open ON reminder (shoe_id, type) WHERE status IN ('ACTIVE', 'ACKNOWLEDGED');

CREATE INDEX idx_reminder_status ON reminder (status);
